### ISSUE TITLE
resize flicker/redraw

### ISSUE THREAD

**Issue by knalleDK** [ImBaedin/Thpace#8] opened 2021-02-11 22:20 UTC
Is there a way to prevent the redraw? When used on iOS the Safari navbar is triggering af resize event on the first scroll, so thpace is triggering a redraw.

**Comment by ImBaedin** [comment] 2021-02-11 23:42
This is a tough problem to solve, particularly on the library side. This is a [not uncommon](https://medium.com/@susiekim9/how-to-compensate-for-the-ios-viewport-unit-bug-46e78d54af0d) side effect that has been branded a _feature_. The reason it's difficult to solve from this side is because thpace doesn't determine its own size, it simply mirrors the parent.

Assuming you're using it as a background, the best solution might be to increase the height of the container element so that when the viewport expands, it is just exposing what was already there. Although if you were to use CSS for this, it would probably still break since the expanding viewport would make the container expand with it.

As long as the dimensions of the parent of the thpace canvas don't change, thpace _should_ ignore the resize event.

I don't have an iOS device, or else I would attempt to come up with an actual solution. If It's an issue reproducible in mobile chrome, I can try my hand at fixing it and share the solution.

**Comment by knalleDK** [comment] 2021-02-12 08:32
I was thinking of solving it by setting a fixed size for the container (or the canvas itself), but it still reacts on resize event - though it has no need for it really.

**Comment by knalleDK** [comment] 2021-02-13 20:11
Perhaps you can make a version, where the "resize" can be called manually?

**Comment by ImBaedin** [comment] 2021-02-14 17:05
I can implement a setting to prevent automatic resizing, and add a manual resize function. I understand why it's still redrawing, and it's simply an oversight. I will try to get an update pushed and will update the issue when I can.

**Comment by knalleDK** [comment] 2021-02-15 19:26
Sounds great. Looking forward implementing this on a live website :)

**Comment by ImBaedin** [comment] 2021-02-15 19:36
Change has been pushed and published to NPM. Added the new `automaticResize` option and changed the behavior of the internal resize function to only re-init if the parent's container size changes. You can still call this function on the instance.

If you can manage to get a good solution for the mobile browser, it might be a good example to throw in the readme, so let me know!

Closing but feel free to re-open if something doesn't work.

**Closed by ImBaedin** 2021-02-15 19:36 UTC
